# Generated by Django 4.2 on 2023-04-10 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='isTrue',
            new_name='isCorrect',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quizcategory'),
        ),
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quizcategory',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question'),
        ),
    ]
