# Generated by Django 4.2 on 2023-04-11 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_istrue_option_iscorrect_question_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicsIncluded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quizcategory')),
            ],
        ),
    ]
