# Generated by Django 4.2 on 2023-04-12 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_topicsincluded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicsincluded',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='quiz.quizcategory'),
        ),
    ]
