# Generated by Django 4.2 on 2023-04-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_option_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(to='quiz.option'),
        ),
    ]
