# Generated by Django 4.2 on 2023-04-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
    ]
