# Generated by Django 4.2 on 2023-04-15 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
    ]
