version: '3.8' 
services: 
  quizupnow_web:
    container_name: quizupnow_web
    build:
      context: ./app
      dockerfile: Dockerfile.dev  
    command: python manage.py runserver 0.0.0.0:8003
    volumes: 
      - ./app/:/quizupnow/app/   
    ports: 
      - 8003:8003
    depends_on:
      - quizupnow_development_db
    environment:  
      - DEBUG=1
      - SECRET_KEY=setsecretkey
      - ALLOWED_HOSTS=localhost
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=quizupnow_development_db
      - SQL_USER=quizupnow_development_user
      - SQL_PASSWORD=quizupnow_development_password
      - SQL_HOST=quizupnow_development_db
      - SQL_PORT=5432
    restart: always 
  quizupnow_development_db:
    image: postgres:13.0-alpine
    volumes:
      - quizupnow_development_postgres_data:/var/lib/postgresql/data/  
    environment:  
      - POSTGRES_USER=quizupnow_development_user 
      - POSTGRES_PASSWORD=quizupnow_development_password
      - POSTGRES_DB=quizupnow_development_db   

volumes:
  quizupnow_development_postgres_data:

