version: '3.8' 
services: 
  appName_web: 
    build:
      context: ./app
      dockerfile: Dockerfile.dev  
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./app/:/usr/src/app/   
    ports: 
      - 8000:8000
    depends_on:
      - appName_development_db
    environment:  
      - DEBUG=1
      - SECRET_KEY=1a-owqf2mb2+im(d(jedgtylaogc8)0#1bcv3*1j=l^zu6l_nj
      - ALLOWED_HOSTS=localhost
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=appName_development_db
      - SQL_USER=appName_development_user
      - SQL_PASSWORD=appName_development_password
      - SQL_HOST=appName_development_db
      - SQL_PORT=5432
    restart: always 
  appName_development_db:
    image: postgres:13.0-alpine
    volumes:
      - appName_development_postgres_data:/var/lib/postgresql/data/  
    environment:  
      - POSTGRES_USER=appName_development_user 
      - POSTGRES_PASSWORD=appName_development_password
      - POSTGRES_DB=appName_development_db   

volumes:
  appName_development_postgres_data:

