version: '3.8'

services:
  appName_nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - appName_web
    ports:
      - 80:80
    volumes:
      - ./app/staticfiles/:/appName/app/staticfiles
      - ./app/mediafiles:/appName/app/mediafiles


  appName_web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn appName.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/staticfiles/:/appName/app/staticfiles
      - ./app/mediafiles:/appName/app/mediafiles
    expose:
      - 8000 
    depends_on:
      - appName_local_production_db 
    restart: always 
    environment:  
      - DEBUG=1
      - SECRET_KEY=setsecretkey
      - ALLOWED_HOSTS=localhost
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=appName_local_production_db
      - SQL_USER=appName_local_production_user
      - SQL_PASSWORD=appName_local_production_password
      - SQL_HOST=appName_local_production_db
      - SQL_PORT=5432

  appName_local_production_db:
    image: postgres:13.0-alpine
    volumes:
      - appName_local_production_postgres_data:/var/lib/postgresql/data/  
    environment:
      - POSTGRES_USER=appName_local_production_user 
      - POSTGRES_PASSWORD=appName_local_production_password
      - POSTGRES_DB=appName_local_production_db   


volumes:
  appName_local_production_postgres_data: 

