version: '3.3'

services: 
  quizupnow_nginx: 
    build: ./nginx
    depends_on:
      - quizupnow_web 
    ports:
      - 80:80
    volumes:
      - ./app/staticfiles/:/quizupnow/app/staticfiles
      - ./app/mediafiles:/quizupnow/app/mediafiles

  quizupnow_web: 
    build:
      context: ./app
      dockerfile: Dockerfile.prod 

    command: gunicorn quizupnow.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/staticfiles/:/quizupnow/app/staticfiles
      - ./app/mediafiles:/quizupnow/app/mediafiles
    expose:
      - 8000
    depends_on:
      - quizupnow_production_db 
    restart: always 
    environment:  
      - DEBUG=0
      - SECRET_KEY=setsecretkey
      - ALLOWED_HOSTS=localhost
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=quizupnow_production_db
      - SQL_USER=quizupnow_production_user
      - SQL_PASSWORD=quizupnow_production_password
      - SQL_HOST=quizupnow_production_db
      - SQL_PORT=5432

  quizupnow_production_db:
    image: postgres:13.0-alpine
    volumes:
      - quizupnow_production_postgres_data:/var/lib/postgresql/data/  
    environment:
      - POSTGRES_USER=quizupnow_production_user 
      - POSTGRES_PASSWORD=quizupnow_production_password
      - POSTGRES_DB=quizupnow_production_db   


volumes:
  quizupnow_production_postgres_data: 



