FROM python:3
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
WORKDIR /appName/app 
COPY ./requirements.txt .  
RUN pip install -r requirements.txt
COPY . . 
ENTRYPOINT ["/appName/app/entrypoint.prod.sh"]


